
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("pa_pic/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("pa_pic", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit pa_pic</h1>
</div>

<table class="table table-border table-bordered table-hover">
    <tr>
        <td align="right">
            <label for="thumb_small">Thumb Of Small</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("thumb_small", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="thumb_middle">Thumb Of Middle</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("thumb_middle", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="thumb_large">Thumb Of Large</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("thumb_large", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="origin_url">Origin Of Url</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("origin_url", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
