
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("pa_pic/new", "Create pa_pic")) ?>
</div>

<?php echo $this->tag->form(array("pa_pic/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search pa_pic</h1>
</div>

<table class="table table-border table-bordered table-hover">
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="thumb_small">Thumb Of Small</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("thumb_small", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="thumb_middle">Thumb Of Middle</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("thumb_middle", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="thumb_large">Thumb Of Large</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("thumb_large", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="origin_url">Origin Of Url</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("origin_url", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
