
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("pa_collection/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("pa_collection", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit pa_collection</h1>
</div>

<table class="table table-border table-bordered table-hover">
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("content", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="tid">Tid</label>
        </td>
        <td align="left">
            <?php $this->partial('partials/cate', ['name'=>'tid']) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pid">Pid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="published_at">Published</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("published_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="deleted_at">Deleted</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("deleted_at", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
