<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("pa_collection/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("pa_collection/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse table table-border table-bordered table-hover" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th style="width:70px">Name</th>
            <th style="width:70px">Description</th>
            <th style="width:200px">Content</th>
            <th>Tid</th>
            <th>Pid</th>
            <th>Created</th>
            <th>Published</th>
            <th>Deleted</th>
            <th style="width:125px">操作</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $pa_collection) { ?>
        <tr>
            <td><?php echo $pa_collection->id ?></td>
            <td><?php echo $pa_collection->name ?></td>
            <td><?php echo $pa_collection->description ?></td>
            <td><?php echo mb_substr($pa_collection->content, 0, 100, 'utf-8').'...' ?></td>
            <td><?php echo $pa_collection->tid ?></td>
            <td><?php echo $pa_collection->pid ?></td>
            <td><?php echo $pa_collection->created_at ?></td>
            <td><?php echo $pa_collection->published_at ?></td>
            <td><?php echo $pa_collection->deleted_at ?></td>
            <td>
                <?php echo $this->tag->linkTo(array("pa_collection/edit/" . $pa_collection->id, "编辑", "class"=>"btn btn-primary")); ?>
                <?php echo $this->tag->linkTo(array("pa_collection/delete/" . $pa_collection->id, "删除", "class"=>"btn btn-danger")); ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("pa_collection/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("pa_collection/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("pa_collection/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("pa_collection/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
