
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("pa_animate/save") ?>
<legend>编辑</legend>

<div class="cl pd-5 bg-1 bk-gray mt-10 mb-10">
    <span class="l">
        <a href="<?php echo $this->url->get("pa_animate/index") ?>" class="btn btn-danger radius">
            <i class="Hui-iconfont">&#xe678;</i> 返回
        </a>
        <?php echo $this->tag->submitButton(array("保存","class"=>"btn btn-primary")) ?>
    </span>
</div>

<div class="mt-20">
<table class="table table-border table-bordered table-hover table-striped">
    <tr>
        <td align="right">
            <label for="aid">Aid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("aid", "type" => "number", "class"=>"input-text")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30, "class"=>"input-text")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30, "class"=>"input-text")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textArea(array("content", "cols" => 30, "rows" => 4, "class"=>"textarea")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pid">Pid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pid", "type" => "number", "class"=>"input-text pa-pic-input")) ?>
            <?php $this->partial("partials/picture") ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="vid">Vid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("vid", "size" => 30, "class"=>"input-text")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30, "class"=>"input-text")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="published_at">Published</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("published_at", "size" => 30, "class"=>"input-text")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton(array("保存", "class"=>"btn btn-success")) ?></td>
    </tr>
</table>
</div>
</form>
