<?php echo $this->getContent(); ?>
<?php echo $this->tag->form(array("pa_animate/create", "class" => "form form-horizontal")) ?>

<div class="cl pd-5 bg-1 bk-gray mt-10 mb-10">
    <span class="l">
        <a href="<?php echo $this->url->get("pa_animate/index") ?>" class="btn btn-danger radius">
            <i class="Hui-iconfont">&#xe678;</i> 返回
        </a>
        <?php echo $this->tag->submitButton(array("保存", "class" => "btn btn-primary")) ?>
    </span>
</div>

<legend>添加</legend>

<div class="row cl">
    <label for="aid" class="form-label col-xs-2 col-sm-2">Aid</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("aid", "type" => "number", "class" => "input-text")) ?>
    </div>
    <label for="name" class="form-label col-xs-2 col-sm-2">Name</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "input-text")) ?>
    </div>
</div>
<div class="row cl">
    <label for="description" class="form-label col-xs-2 col-sm-2">Description</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("description", "size" => 30, "class" => "input-text")) ?>
    </div>
    <label for="content" class="form-label col-xs-2 col-sm-2">Content</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textArea(array("content", "cols" => 30, "rows" => 4, "class" => "textarea")) ?>
    </div>
</div>
<div class="row cl">
    <label for="pid" class="form-label col-xs-2 col-sm-2">Pid</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("pid", "type" => "number", "class" => "input-text pa-pic-input")) ?>
        <?php $this->partial("partials/picture") ?>
    </div>
    <label for="vid" class="form-label col-xs-2 col-sm-2">Vid</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("vid", "size" => 30, "class" => "input-text")) ?>
    </div>
</div>
<div class="row cl">
    <label for="created_at" class="form-label col-xs-2 col-sm-2">Created</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("created_at", "size" => 30, "class" => "input-text")) ?>
    </div>
    <label for="published_at" class="form-label col-xs-2 col-sm-2">Published</label>
    <div class="formControls col-xs-4 col-sm-4">
        <?php echo $this->tag->textField(array("published_at", "size" => 30, "class" => "input-text")) ?>
    </div>
</div>

<div class="row cl">
    <?php echo $this->tag->submitButton(array("新增", "class" => "btn btn-success")) ?>
    <input type="reset" class="btn btn-danger" value="取消">
</div>

</form>
