
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("pa_article/new", "Create pa_article")) ?>
</div>

<?php echo $this->tag->form(array("pa_article/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search pa_article</h1>
</div>

<table class="table table-border table-bordered table-hover">
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textArea(array("content", "cols" => 50, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="published_at">Published</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("published_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="views">Views</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("views", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
