
<?php echo $this->tag->form("pa_rec/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("pa_rec", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create pa_rec</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="url">Url</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("url", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="aid">Aid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("aid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="position">Position</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("position", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
