<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("pa_rec/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("pa_rec/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Url</th>
            <th>Aid</th>
            <th>Position</th>
            <th>Description</th>
            <th>Status</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $pa_rec) { ?>
        <tr>
            <td><?php echo $pa_rec->id ?></td>
            <td><?php echo $pa_rec->url ?></td>
            <td><?php echo $pa_rec->aid ?></td>
            <td><?php echo $pa_rec->position ?></td>
            <td><?php echo $pa_rec->description ?></td>
            <td><?php echo $pa_rec->status ?></td>
            <td><?php echo $this->tag->linkTo(array("pa_rec/edit/" . $pa_rec->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("pa_rec/delete/" . $pa_rec->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("pa_rec/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("pa_rec/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("pa_rec/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("pa_rec/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
