
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("pa_category/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("pa_category", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit pa_category</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pid">Pid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("pid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lft">Lft</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lft", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="rgt">Rgt</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rgt", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
