<?php
use Mptt\Mptt as Mptt;

class AdminController extends ControllerBase
{
    public function initialize()
    {
        $this->tag->setTitle(' · 后台');
        $this->assets->addCss('css/H-ui.min.css')
            ->addCss('css/H-ui.admin.css')
            ->addCss('css/iconfont.css')
            ->addCss('css/admin.css');
        $this->assets->addJs('js/jquery.min.js')
            ->addJs('js/H-ui.js')
            ->addJs('js/H-ui.admin.js')
            ->addJs('js/bootstrap-modalmanager.js')
            ->addJs('js/bootstrap-modal.js')
            ->addJs('js/admin.js');
        
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    
    public function indexAction()
    {
        
    }

    /**
     * @return \Phalcon\Http\Response|\Phalcon\Http\ResponseInterface
     */
    public function selectImageAction()
    {
        $pa_pic = PaPic::find(array(
            'order' => "id DESC",
            'limit' => 10
        ));

        $data = array();
        foreach ($pa_pic as $pic) {
            $data[] = array(
                'id'   => $pic->id,
                'url' => $pic->thumb_small
            );
        }

        return $this->response->setJsonContent(array(
            "status" => "OK",
            "data" => $data
        ));
    }

    public function selectMenuAction($ids)
    {
        $data = array();
        if($ids == 0){
            $pa_cates = Mptt::listById(0);
        }else{
            $pa_cates = Mptt::listByRange($ids);
        }

        foreach ($pa_cates as $cate) {
            $data[] = array(
                'id'   => $cate->id,
                'name' => $cate->name
            );
        }
        return $this->response->setJsonContent(array(
            "status" => "OK",
            "data" => $data
        ));
    }
}

