<?php
use Mptt\Mptt as Mptt;

/**
 * Class IndexController
 */
class IndexController extends ControllerBase
{
    public function initialize()
    {
        $this->tag->setTitle(' · 主页 ');
        $this->assets->addCss('css/index.css')
            ->addCss('css/bootstrap.css')
            ->addCss('css/unslider.min.css')
            ->addJs('js/jquery.min.js')
            ->addJs('js/unslider.min.js')
            ->addJs('js/index.js');
        
        $first_cates = Mptt::listById(0);
        foreach ($first_cates as $second_cont)
        {
            $navs[] = $second_cont->name;
        }
        $this->view->setVar('navs', $navs);// 导航
        $banner = $this->url->getStatic('img/banner/banner.jpg');
        $this->view->setVar("banner", $banner);// banner图

        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 查询所有collection
     */
    public function indexAction()
    {
        $collections = null;
        // 轮播
        $bannnerImages = PaRec::find(array(
            "position = 0",
            "status = 1",
            'order'=>'id DESC'
        ));
        $phql = "select A.id AS id, A.url AS url, A.aid AS aid, B.name AS name ,B.description AS description from PaRec AS A".
        " LEFT JOIN PaCollection AS B ON A.aid = B.id WHERE A.position = 1 AND A.status = 1 ORDER BY A.id LIMIT 4";
        $sideImages = $this->modelsManager->executeQuery($phql);

        // 所有内容
        $first_cates = Mptt::listById(0);
        // Todo: 改为IN查询！！！！！！！！

        foreach ($first_cates as $second_cont)
        {
            $collections[] = array("area"=>$second_cont, "content"=>$this->area($second_cont->id));
        }

        $this->view->setVar('bannerImages', $bannnerImages);
        $this->view->setVar('sideImages', $sideImages);
        $this->view->setVar('collections', $collections);
    }

    /**
     * 传递 aid
     * 输出 collection 以及对应的 animates
     * @param $aid
     */
    public function vAction($aid)
    {
        $collect = PaCollection::findFirst($aid);
        $picture = $collect->getPaPic();

        $phql = "SELECT A.id AS id, A.aid AS aid, A.name AS name, A.description AS description, A.content AS content, A.published_at AS published_at, B.origin_url AS url ".
            "FROM PaAnimate AS A ".
            "LEFT JOIN PaPic AS B ".
            "ON A.pid = B.id ".
            "WHERE A.aid =".$aid.
            " ORDER BY A.created_at DESC";
        $animates = $this->modelsManager->executeQuery($phql);

        $this->view->setVar('collect', $collect);
        $this->view->setVar('picture', $picture);
        $this->view->setVar('animates', $animates);
    }

    /**
     * 选择一个cate下的所有10个子collection
     * @param $cid
     * @return \Phalcon\Mvc\Model\QueryInterface
     */
    public function area($cid)
    {
        // 连表查询
        $phql = "SELECT A.id AS id, A.name AS name, A.description AS description, B.origin_url AS url ".
            "FROM PaCollection AS A ".
            "LEFT JOIN PaPic AS B ".
            "ON A.pid = B.id ".
            "WHERE A.tid = ".$cid.
            "ORDER BY A.created_at DESC ".
            "LIMIT 8";
        return $this->modelsManager->executeQuery($phql);
    }

//    public function tagAction()
//    {
//        /* 插入节点 */
////        Mptt::insert(1, "国产");
//    }

    public function mapAction()
    {
        $first_cates = Mptt::listById(0);
        foreach ($first_cates as $_fcate)
        {
            $cates[] = Mptt::listByRange($_fcate->id);
        }
        $this->view->setVar('cates', $cates);
    }

}

