<?php
 
use Phalcon\Mvc\Model\Criteria;
use Phalcon\Paginator\Adapter\Model as Paginator;
use Mptt\Mptt as Mptt;

class PaCategoryController extends AdminController
{
    public function initialize()
    {
        $this->view->setTemplateAfter('admin');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Index action
     */
    public function indexAction()
    {
        $this->persistent->parameters = null;
    }

    /**
     * Searches for pa_category
     */
    public function searchAction()
    {

        $numberPage = 1;
        if ($this->request->isPost()) {
            $query = Criteria::fromInput($this->di, "PaCategory", $_POST);
            $this->persistent->parameters = $query->getParams();
        } else {
            $numberPage = $this->request->getQuery("page", "int");
        }

        $parameters = $this->persistent->parameters;
        if (!is_array($parameters)) {
            $parameters = array();
        }
        $parameters["order"] = "id";

        $pa_category = PaCategory::find($parameters);
        if (count($pa_category) == 0) {
            $this->flash->notice("The search did not find any pa_category");

            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "index"
            ));
        }

        $paginator = new Paginator(array(
            "data" => $pa_category,
            "limit"=> 10,
            "page" => $numberPage
        ));

        $this->view->page = $paginator->getPaginate();
    }

    /**
     * Displays the creation form
     */
    public function newAction()
    {

    }
    public function childAction($id)
    {
        $this->tag->setDefault('pid', $id);
    }
    /**
     * Edits a pa_category
     *
     * @param string $id
     */
    public function editAction($id)
    {

        if (!$this->request->isPost()) {

            $pa_category = PaCategory::findFirstByid($id);
            if (!$pa_category) {
                $this->flash->error("pa_category was not found");

                return $this->dispatcher->forward(array(
                    "controller" => "pa_category",
                    "action" => "index"
                ));
            }

            $this->view->id = $pa_category->id;

            $this->tag->setDefault("id", $pa_category->id);
            $this->tag->setDefault("name", $pa_category->name);
            $this->tag->setDefault("pid", $pa_category->pid);
            $this->tag->setDefault("lft", $pa_category->lft);
            $this->tag->setDefault("rgt", $pa_category->rgt);
            
        }
    }

    /**
     * Creates a new pa_category
     */
    public function createAction()
    {

        if (!$this->request->isPost()) {
            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "index"
            ));
        }

        if (!Mptt::insert($this->request->getPost("pid"), $this->request->getPost("name"))) {
            $this->flash->error("插入失败");

            $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "new"
            ));
        }

        $this->flash->success("插入成功");

        return $this->dispatcher->forward(array(
            "controller" => "pa_category",
            "action" => "index"
        ));

    }

    /**
     * Saves a pa_category edited
     *
     */
    public function saveAction()
    {

        if (!$this->request->isPost()) {
            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "index"
            ));
        }

        $id = $this->request->getPost("id");

        $pa_category = PaCategory::findFirstByid($id);
        if (!$pa_category) {
            $this->flash->error("pa_category does not exist " . $id);

            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "index"
            ));
        }

        $pa_category->name = $this->request->getPost("name");
        $pa_category->pid = $this->request->getPost("pid");
        $pa_category->lft = $this->request->getPost("lft");
        $pa_category->rgt = $this->request->getPost("rgt");
        

        if (!$pa_category->save()) {

            foreach ($pa_category->getMessages() as $message) {
                $this->flash->error($message);
            }

            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "edit",
                "params" => array($pa_category->id)
            ));
        }

        $this->flash->success("pa_category was updated successfully");

        return $this->dispatcher->forward(array(
            "controller" => "pa_category",
            "action" => "index"
        ));

    }

    /**
     * Deletes a pa_category
     *
     * @param string $id
     */
    public function deleteAction($id)
    {

        $pa_category = PaCategory::findFirstByid($id);
        if (!$pa_category) {
            $this->flash->error("pa_category was not found");

            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "index"
            ));
        }

        if (!$pa_category->delete()) {

            foreach ($pa_category->getMessages() as $message) {
                $this->flash->error($message);
            }

            return $this->dispatcher->forward(array(
                "controller" => "pa_category",
                "action" => "search"
            ));
        }

        $this->flash->success("pa_category was deleted successfully");

        return $this->dispatcher->forward(array(
            "controller" => "pa_category",
            "action" => "index"
        ));
    }

}
