<?php
 
use Phalcon\Mvc\Model\Criteria;
use Phalcon\Paginator\Adapter\Model as Paginator;

class PaCollectionController extends AdminController
{
    public function initialize()
    {
        $this->view->setTemplateAfter('admin');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * Index action
     */
    public function indexAction()
    {
        $this->persistent->parameters = null;
    }

    /**
     * Searches for pa_collection
     */
    public function searchAction()
    {

        $numberPage = 1;
        if ($this->request->isPost()) {
            $query = Criteria::fromInput($this->di, "PaCollection", $_POST);
            $this->persistent->parameters = $query->getParams();
        } else {
            $numberPage = $this->request->getQuery("page", "int");
        }

        $parameters = $this->persistent->parameters;
        if (!is_array($parameters)) {
            $parameters = array();
        }
        $parameters["order"] = "id";

        $pa_collection = PaCollection::find($parameters);
        if (count($pa_collection) == 0) {
            $this->flash->notice("The search did not find any pa_collection");

            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "index"
            ));
        }

        $paginator = new Paginator(array(
            "data" => $pa_collection,
            "limit"=> 10,
            "page" => $numberPage
        ));

        $this->view->page = $paginator->getPaginate();
    }

    /**
     * Displays the creation form
     */
    public function newAction()
    {

    }

    /**
     * Edits a pa_collection
     *
     * @param string $id
     */
    public function editAction($id)
    {

        if (!$this->request->isPost()) {

            $pa_collection = PaCollection::findFirstByid($id);
            if (!$pa_collection) {
                $this->flash->error("pa_collection was not found");

                return $this->dispatcher->forward(array(
                    "controller" => "pa_collection",
                    "action" => "index"
                ));
            }

            $this->view->id = $pa_collection->id;

            $this->tag->setDefault("id", $pa_collection->id);
            $this->tag->setDefault("name", $pa_collection->name);
            $this->tag->setDefault("description", $pa_collection->description);
            $this->tag->setDefault("content", $pa_collection->content);
            $this->tag->setDefault("tid", $pa_collection->tid);
            $this->tag->setDefault("pid", $pa_collection->pid);
            $this->tag->setDefault("created_at", $pa_collection->created_at);
            $this->tag->setDefault("published_at", $pa_collection->published_at);
            $this->tag->setDefault("deleted_at", $pa_collection->deleted_at);
            
        }
    }

    /**
     * Creates a new pa_collection
     */
    public function createAction()
    {

        if (!$this->request->isPost()) {
            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "index"
            ));
        }

        $pa_collection = new PaCollection();

        $pa_collection->name = $this->request->getPost("name");
        $pa_collection->description = $this->request->getPost("description");
        $pa_collection->content = $this->request->getPost("content");
        $pa_collection->tid = $this->request->getPost("tid");
        $pa_collection->pid = $this->request->getPost("pid");
//        $pa_collection->created_at = $this->request->getPost("created_at");
        $pa_collection->published_at = date("Y-m-d H:i:s", strtotime($this->request->getPost("published_at")));
//        $pa_collection->published_at = $this->request->getPost("published_at")
        $pa_collection->deleted_at = date("Y-m-d H:i:s", strtotime($this->request->getPost("deleted_at")));
//        $pa_collection->deleted_at = $this->request->getPost("deleted_at")
        if (!$pa_collection->save()) {
            foreach ($pa_collection->getMessages() as $message) {
                $this->flash->error($message);
            }

            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "new"
            ));
        }

        $this->flash->success("pa_collection was created successfully");

        return $this->dispatcher->forward(array(
            "controller" => "pa_collection",
            "action" => "index"
        ));

    }

    /**
     * Saves a pa_collection edited
     *
     */
    public function saveAction()
    {

        if (!$this->request->isPost()) {
            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "index"
            ));
        }

        $id = $this->request->getPost("id");

        $pa_collection = PaCollection::findFirstByid($id);
        if (!$pa_collection) {
            $this->flash->error("pa_collection does not exist " . $id);

            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "index"
            ));
        }

        $pa_collection->name = $this->request->getPost("name");
        $pa_collection->description = $this->request->getPost("description");
        $pa_collection->content = $this->request->getPost("content");
        $pa_collection->tid = $this->request->getPost("tid");
        $pa_collection->pid = $this->request->getPost("pid");
        $pa_collection->created_at = date('Y-m-d H:i:s', strtotime($this->request->getPost("created_at")));
        $pa_collection->published_at = date('Y-m-d H:i:s', strtotime($this->request->getPost("published_at")));
        $pa_collection->deleted_at = date('Y-m-d H:i:s', strtotime($this->request->getPost("deleted_at")));
        

        if (!$pa_collection->save()) {

            foreach ($pa_collection->getMessages() as $message) {
                $this->flash->error($message);
            }

            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "edit",
                "params" => array($pa_collection->id)
            ));
        }

        $this->flash->success("pa_collection was updated successfully");

        return $this->dispatcher->forward(array(
            "controller" => "pa_collection",
            "action" => "index"
        ));

    }

    /**
     * Deletes a pa_collection
     *
     * @param string $id
     */
    public function deleteAction($id)
    {

        $pa_collection = PaCollection::findFirstByid($id);
        if (!$pa_collection) {
            $this->flash->error("pa_collection was not found");

            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "index"
            ));
        }

        if (!$pa_collection->delete()) {

            foreach ($pa_collection->getMessages() as $message) {
                $this->flash->error($message);
            }

            return $this->dispatcher->forward(array(
                "controller" => "pa_collection",
                "action" => "search"
            ));
        }

        $this->flash->success("pa_collection was deleted successfully");

        return $this->dispatcher->forward(array(
            "controller" => "pa_collection",
            "action" => "index"
        ));
    }

}
