<?php
use SimpleHtml\SimpleHtml as SimpleHtml;
class SnatchController extends AdminController
{
    public function initialize()
    {
        $this->view->setTemplateAfter('admin');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    
    public function indexAction()
    {

    }
    
    /**
     * 优酷解析
     */
    public function  youkuAction()
    {
        if(!$this->request->isPost()){
            $this->flash->error('not permit');
            return;
        }
        $url = $this->request->getPost("url");
        $cate = $this->request->getPost("cate");

        $_youkuHtml = SimpleHtml::file_get_html($url);
        $data = [];
        $aid = null;
        $pid = null;
        $match = null;

        /**
         * 生成 pic 实体
         */

        $name = $_youkuHtml->find('h1.title span.name', 0)->plaintext;
        $content = trim($_youkuHtml->find('.detail .short', 0)->plaintext);
        $alia = $_youkuHtml->find('.row1 .alias', 0)->title;
        $picture = $_youkuHtml->find('.thumb img', 0)->src;
        $ctimestamp = strtotime(date("Y-m-d H:i:s"));

        $this->db->begin();// 事务开始
        $pa_pic = new PaPic();
        $pa_pic->thumb_large = $picture;
        $pa_pic->thumb_middle = $picture;
        $pa_pic->thumb_small = $picture;
        $pa_pic->origin_url = $picture;
        if(!$pa_pic->save()){
            $this->db->rollback();
            $pid = -1;
            foreach ($pa_pic->getMessages() as $message) {
                $this->flash->error($message);
            }
        }else{
            $pid = $pa_pic->id;
        }
        /**
         * 生成 collection 实体
         */
        $pa_collection = new PaCollection();
        $pa_collection->name = $name;
        $pa_collection->description = $alia;
        $pa_collection->content = $content;
        $pa_collection->tid = $cate;
        $pa_collection->pid = $pid;
        $pa_collection->created_at = date("Y-m-d H:i:s", $ctimestamp);
        $pa_collection->published_at = date("Y-m-d H:i:s", $ctimestamp + 1);
        $pa_collection->deleted_at = '';


        if(!$pa_collection->save()){
            $this->db->rollback();
            $aid = -1;
            foreach ($pa_collection->getMessages() as $message) {
                $this->flash->error($message);
            }
        }else{
            $aid = $pa_collection->id;
        }
        /**
         * 生成 animate 实体
         */
        foreach ($_youkuHtml->find('.coll_2') as $item)
        {
            foreach ($item->find('ul li a') as $_animate)
            {
                $data[] = ["title"=>$_animate->title, "href"=>$_animate->href];
            }
        }
        $atimestamp = strtotime(date("Y-m-d H:i:s"));
        $i = 0;
        foreach ($data as $_ani)
        {
            $pa_animate = new PaAnimate();
            $pa_animate->aid = $aid;
            $pa_animate->created_at = date("Y-m-d H:i:s", $atimestamp + $i);
            $pa_animate->published_at  = date("Y-m-d H:i:s", $atimestamp + 1 + $i);
            $pa_animate->name = $_ani['title'];
            $pa_animate->description = '这是默认生成的';
            $pa_animate->content = '这是默认生成的';
            preg_match("/id\\_([\\w=]+)\\.html/i",$_ani['href'], $match);
            $pa_animate->vid = $match[1];
            $pa_animate->pid = $pid;
            if (!$pa_animate->save()) {
                $this->db->rollback();
                foreach ($pa_animate->getMessages() as $message) {
                    $this->flash->error($message);
                }
                return;
            }
            $i += 2;
        }
        // 提交事务
        $this->db->commit();
        $this->flash->success("you have succeed!!!");
        $this->response->redirect('snatch/index');
    }
}

